version: "3.9"

services:
  web:
    build:
      context: .
    command: >
      sh -c "python /app/manage.py migrate &&
             python /app/manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  
  db:
    image: postgres:12.13
    env_file:
      - ./.env.dev
    ports:
      - "5433:5432"
  
  redis:
    image: redis:latest

  celery:
    restart: always
    build: .
    command: celery -A DockerizedProject worker -l INFO
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
      - web